name: 2nd-workflow

# 'on' hamesha lower case mein hota hai aur 'Push' ki jagah 'push'
on:
  push:
    branches: [ "main" ]

jobs:
  run-test:
    # 'runs-on' (plural) hota hai
    runs-on: ubuntu-latest
    steps:
      - name: Running Tests
        run: echo "test is running"
        
      - name: Test Status
        run: echo "test successful"

  # Deploy job tabhi chalna chahiye jab test success ho
  deploy-app:
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "Deploying the application..."