name: PR-Check

on: pull_request  

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "New PR ,CHECK START!"

      - name: Time Check
        run: date

  final-job:
    runs-on: ubuntu-latest
    steps:
      - name: Bye
        run: echo "PR check khatam."