name: My First Automation

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create hello file
        run: echo "Hello world, this is me" > file.txt

      - name: Upload my file
        uses: actions/upload-artifact@v4
        with:
          name: my-file
          path: file.txt